config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable

  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  responders :flash
  respond_to :html
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    protected

    def update_resource(resource, params)
      resource.update_without_password(params)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.slim
footer.row
  .columns
    p &copy; Rails5App #{Time.zone.today.year}

app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(data-alert class="alert-box #{type}" tabindex="0" aria-live="assertive" role="alertdialog")
    = content
    button.close(tabindex="0" aria-label="Close Alert") &times;

app/views/application/_navigation.html.slim
nav.top-bar( data-topbar )

  ul.title-area
    li.name
      h1 = link_to "Rails5App", root_path
    li.toggle-topbar
      a(href="#")
        i.fi-list

  section.top-bar-section
    = render "navigation_main"
    = render "navigation_user"

app/views/application/_navigation_main.html.slim
ul.left
  - if user_signed_in?
    = active_link_to "Home", root_path, active: :exclusive, wrap_tag: :li

app/views/application/_navigation_user.html.slim
ul.right
  - if user_signed_in?
    li.has-dropdown
      a.user-dropdown(href="#") = current_user.full_name_with_email
      ul.dropdown
        li
          = link_to "Edit profile", edit_user_registration_path
        li
          = link_to "Sign out", destroy_user_session_path
  - else
    = active_link_to "Sign in", new_user_session_path, active: :exclusive, wrap_tag: :li
    = active_link_to "Sign up", new_user_registration_path, active: :exclusive, wrap_tag: :li

app/views/layouts/application.html.slim
doctype html

html class="no-js" lang="en"

  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="robots" content="NOODP,NOYDIR"

    = metamagic site: "Rails5App", title: %i(title site), separator: " - "
    = csrf_meta_tags

    = stylesheet_link_tag :application

    = javascript_include_tag "vendor/modernizr"

    = javascript_tag "window.App = {}"

    == analytics_init if GA.tracker

  body
    #root
      = render "navigation"
      = render "messages"

      = yield

    = render "footer"

    javascript:
      App.currentUserData = #{{current_user.to_json}};

    = javascript_include_tag :application

app/views/pages/home.html.slim
.row
  .columns
    h2
      /= title("Home")

app/views/users/shared/_links.html.slim
h6 Anything else?
ul.links
  - if controller_name != "sessions"
    li = link_to "Sign in", new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != "registrations"
    li = link_to "Create a new account", new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != "passwords"
    li = link_to "Forgot your password?", new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != "confirmations"
    li = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
    li = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)